language: groovy
jdk:
- oraclejdk7
- oraclejdk8
before_script:
- chmod +x ./shiro3/gradlew
script: cd shiro3 && ./gradlew clean :grails-shiro:test :cli-tests:test :wildcard-realm:integrationTest --stacktrace
