env:
  - TERM: dumb
jdk:
  - oraclejdk7
  - oraclejdk8
before_cache:
  - find $HOME/.gradle/caches/ -type f -name "*.lock" -delete
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - cd ./shiro3
  - chmod +x ./gradlew
script: ./gradlew clean :grails-shiro:test :cli-tests:test :wildcard-realm:integrationTest -i

